#!/usr/bin/env python3
import asyncio
from tcp import Servidor
import re

msganterior = b''

def validar_nome(nome):
    return re.match(br'^[a-zA-Z][a-zA-Z0-9_-]*$', nome) is not None


def sair(conexao):
    print(conexao, 'conexão fechada')
    conexao.fechar()


def dados_recebidos(conexao, dados):
    global msganterior

    dados = dados + msganterior
    if dados == b'':
        return sair(conexao)
    
    dadosatual = dados.split(b'\n')

    if dados.endswith(b'\n'):
        msganterior = b''
    else:
        msganterior = dadosatual[len(dadosatual)-1]

    if dadosatual[0].startswith(b'PING'):
        conexao.enviar(b':server PONG server :' + dadosatual[0].split(b' ', 1)[1] + b'\n')

    #if dadosatual[0].startswith(b'NICK'):
        
    print(conexao, dados)


def conexao_aceita(conexao):
    print(conexao, 'nova conexão')
    conexao.registrar_recebedor(dados_recebidos)

servidor = Servidor(6667)
servidor.registrar_monitor_de_conexoes_aceitas(conexao_aceita)
asyncio.get_event_loop().run_forever()
